# Generated by Django 4.2.4 on 2023-08-08 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('description', models.CharField(max_length=1000)),
                ('timezone', models.CharField(max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.CharField(max_length=1000)),
                ('startDate', models.DateTimeField(auto_now=True)),
                ('endDate', models.DateTimeField(blank=True)),
                ('allDay', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('email', models.CharField(max_length=180)),
                ('phoneNumber', models.CharField(max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='UserCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kz.calendars')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kz.users')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kz.users')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=180)),
                ('value', models.CharField(max_length=180)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kz.users')),
            ],
        ),
        migrations.CreateModel(
            name='EventsNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kz.notifications')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=180)),
                ('calendar_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kz.calendars')),
                ('event_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kz.events')),
            ],
        ),
    ]
